services:

  postgres:
    image: postgres:16.2
    hostname: postgres-16.2-bbt3104-lab6
    container_name: postgres-16.2-bbt3104-lab6
    restart: always
    shm_size: 1g
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5trathm0re
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./container-volumes/postgresql/var-lib-postgresql-data:/var/lib/postgresql/data
      - ./container-volumes/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./container-volumes/postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  pgadmin4:
    image: elestio/pgadmin:REL-8_13
    hostname: pgadmin-REL-8_13-bbt3104-lab6
    container_name: pgadmin-REL-8_13-bbt3104-lab6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@strathmore.edu
      PGADMIN_DEFAULT_PASSWORD: 5trathm0re
      PGADMIN_LISTEN_PORT: 8080
    ports:
    - 8081:8080
    volumes:
      - ./container-volumes/postgresql/pgadmin/servers.json:/pgadmin4/servers.json

  mysql:
    image: mysql:8.3.0
    hostname: mysql-8.3.0-bbt3104-lab6
    container_name: mysql-8.3.0-bbt3104-lab6
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 5trathm0re
    volumes:
      # To store the server's configuration file in the host
      - ./container-volumes/mysql/etc-mysql/my.cnf:/etc/mysql/my.cnf
      # To store the server's data persistently in the host
      - ./container-volumes/mysql/var-lib-mysql:/var/lib/mysql
      # To run the SQL scripts used to create the required databases
      - ./container-volumes/mysql/init-scripts:/docker-entrypoint-initdb.d/
    command: >
      /bin/bash -c "
      chmod 644 /etc/mysql/my.cnf &&
      exec docker-entrypoint.sh mysqld
      "