# Specifies the version of Docker compose that is being used.
# Then informs Docker compose that what follows are configurations of the
# services (containers) that form the cluster.
version: "3.9"
services:

# Be patient and wait for the server to display "ready for connections" in the
# logs. There are a total of 4 "ready for connections" messages in the logs.

  mysql:
    image: mysql:8.0.35
    hostname: mysql-bbt3104
    container_name: mysql-bbt3104
    ports:
      - 33006:3306
    environment:
      MYSQL_ROOT_PASSWORD: 5trathm0re
    volumes:
      - ./mysql/sample-data:/docker-entrypoint-initdb.d/
      - ./mysql/var-lib-mysql:/var/lib/mysql

  postgres:
    image: postgres:16.2
    hostname: postgres-bbt3104
    container_name: postgres-bbt3104
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5trathm0re
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/var-lib-postgresql-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    hostname: adminer-bbt3104
    container_name: adminer-bbt3104
    restart: always
    ports:
      - 8080:8080